name: Update IPTV URLs Safely

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Drew's raw playlist
        run: |
          curl -s https://raw.githubusercontent.com/Drewski2423/DrewLive/main/MergedCleanPlaylist.m3u8 -o drew.m3u8

      - name: Update URLs in-place while preserving formatting
        run: |
          cp "Watch-point IPTV.m3u8" "Watch-point IPTV.m3u8.bak"
          touch updated.m3u8

          # Read Drew's playlist into a simple two-column format: ChannelName|URL
          awk -F',' '/^#EXTINF/ {name=$NF; getline url; print name "|" url}' drew.m3u8 > drew_map.txt

          while IFS= read -r line; do
            if [[ "$line" == \#EXTINF* ]]; then
              ext_line="$line"
              read -r url_line
              channel_name=$(echo "$ext_line" | awk -F',' '{print $NF}' | xargs)
              # Look up URL in Drew's mapping
              drew_url=$(grep -F "|$channel_name" drew_map.txt | head -n1 | cut -d'|' -f2-)
              echo "$ext_line" >> updated.m3u8
              if [[ -n "$drew_url" ]]; then
                echo "$drew_url" >> updated.m3u8
              else
                echo "$url_line" >> updated.m3u8
              fi
            else
              echo "$line" >> updated.m3u8
            fi
          done < "Watch-point IPTV.m3u8.bak"

          mv updated.m3u8 "Watch-point IPTV.m3u8"

      - name: Commit & push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add "Watch-point IPTV.m3u8"
          git commit -m "Auto-update URLs from Drew's playlist" || echo "No changes"
          git push
