name: Update IPTV Playlist (Preserve Format)

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Fetch Drew's raw playlist
        run: |
          curl -s https://raw.githubusercontent.com/Drewski2423/DrewLive/main/MergedCleanPlaylist.m3u8 -o full.m3u8

      - name: Update URLs while keeping formatting
        run: |
          cp "Watch-point IPTV.m3u8" "Watch-point IPTV.m3u8.bak"

          # Read Drew's playlist into an associative array
          declare -A drew_urls
          while IFS= read -r line; do
            if [[ "$line" == \#EXTINF* ]]; then
              ext_line="$line"
              read -r url_line
              drew_urls["$ext_line"]="$url_line"
            fi
          done < full.m3u8

          # Create a new updated playlist
          : > Watch-point IPTV.m3u8
          while IFS= read -r line; do
            if [[ "$line" == \#EXTINF* ]]; then
              ext_line="$line"
              read -r url_line
              # Replace URL if Drew has one for this channel
              if [[ -n "${drew_urls[$ext_line]}" ]]; then
                echo "$ext_line" >> Watch-point IPTV.m3u8
                echo "${drew_urls[$ext_line]}" >> Watch-point IPTV.m3u8
              else
                echo "$ext_line" >> Watch-point IPTV.m3u8
                echo "$url_line" >> Watch-point IPTV.m3u8
              fi
            fi
          done < "Watch-point IPTV.m3u8.bak"

      - name: Commit & push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add "Watch-point IPTV.m3u8"
          git commit -m "Auto-update playlist URLs" || echo "No changes"
          git push
