name: Update IPTV Playlist (Preserve Format)

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Fetch Drew's raw playlist
        run: |
          curl -s https://raw.githubusercontent.com/Drewski2423/DrewLive/main/MergedCleanPlaylist.m3u8 -o full.m3u8

      - name: Update URLs while keeping formatting
        run: |
          cp "Watch-point IPTV.m3u8" "Watch-point IPTV.m3u8.bak"

          # Create a map of Drew's URLs by the channel name in EXTINF
          awk '/^#EXTINF/ {ext=$0; getline url; map[ext]=url} END {for (i in map) print i "||" map[i]}' full.m3u8 > drews_map.txt

          # Process your playlist
          awk -F'||' 'NR%2==1 {ext=$0; getline url
              found=0
              while((getline line < "drews_map.txt") > 0){
                  split(line,a,"||")
                  if(a[1]==ext){print ext; print a[2]; found=1; break}
              }
              if(found==0){print ext; print url}
          }' "Watch-point IPTV.m3u8.bak" > "Watch-point IPTV.m3u8"

      - name: Commit & push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add "Watch-point IPTV.m3u8"
          git commit -m "Auto-update playlist URLs" || echo "No changes"
          git push
