name: Update IPTV Playlist

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch Drew's raw playlist
        run: |
          curl -s https://raw.githubusercontent.com/Drewski2423/DrewLive/refs/heads/main/MergedCleanPlaylist.m3u8 -o full.m3u8

      - name: Update URLs in playlist
        run: |
          # Create a backup of your playlist
          cp "Watch-point IPTV.m3u8" "Watch-point IPTV.m3u8.bak"

          # Extract the channel identifiers (tvg-id) from your playlist
          grep -oP 'tvg-id="[^"]+"' "Watch-point IPTV.m3u8" | sed 's/tvg-id=//' | tr -d '"' > my_channels.txt

          # Loop through each tvg-id and update URL from Drew's playlist
          while read -r id; do
            # Get the line from Drew's playlist that contains this tvg-id
            url=$(grep -A1 "tvg-id=\"$id\"" full.m3u8 | tail -n1)
            if [ -n "$url" ]; then
              # Replace the URL in your playlist
              awk -v id="$id" -v newurl="$url" '
                $0 ~ "tvg-id=\""id"\"" {print; getline; print newurl; next} 1
              ' "Watch-point IPTV.m3u8.bak" > "Watch-point IPTV.m3u8.tmp" && mv "Watch-point IPTV.m3u8.tmp" "Watch-point IPTV.m3u8"
            fi
          done < my_channels.txt

      - name: Commit & push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add "Watch-point IPTV.m3u8"
          git diff --cached --quiet || git commit -m "Auto-update IPTV URLs"
          git push
